# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
      # Step 4: run full test suite with code coverage
      - run:
          name: run full test suite with code coverage
          command: |
            . venv/bin/activate
            pytest -v --cov=calculator
      # Step 5: Exercise markers
      - run:
          name: run pytest with combination of markers
          command: |
            . venv/bin/activate
            echo "Run with smoke marker"
            pytest -m smoke -v 
            echo "Run with add marker"
            pytest -m add -v 
            echo "Run with mult marker"
            pytest -m mult -v 
            echo "Run with div marker"
            pytest -m div -v 
            echo "Run with power marker"
            pytest -m power -v 
            echo "Run with trig marker"
            pytest -m trig -v 
    